config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :organizations do
    resources :events, except: [:index]
    resources :applications, only: [:create, :destroy, :update] do
      patch '/:id', to: 'applications#update', as: :membership
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :events, only: [] do
    resources :attendances, only: [:create, :destroy]
  end

  resources :users, except: [:destroy]

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  # Api backend routes:

  namespace :api , defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:show, :index]
      resources :organizations, only: [:show, :index]
    end
  end

  namespace :admin do
    resources :organizations,  only: [:index, :update]
  end
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  belongs_to :organization

  validates :user_id, uniqueness: {
    scope: :organization_id,
    message: "You have applied already!"
  }

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected, :enrolled, :waitlisted

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :enroll do
      transitions from: :approved, to: :enrolled
    end

    event :waitlist do
      transitions from: :approved, to: :waitlisted
    end

    event :available do
      transitions from: :waitlisted, to: :enrolled
    end

  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  skip_before_action :verify_authenticity_token

  def current_user
    @user ||= User.find_by(api_key: api_key) unless api_key.nil?
  end

  def api_key
    match = request.headers['AUTHORIZATION']&.match(/^Apikey (.+)/)
    match&.length == 2 ? match[1] : nil
  end

  def authenticate_user!
    head :unauthorized unless current_user.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  # def current_organization_application(organization_id)
  #   current_user.applications.find_by(organization_id: organization_id)
  # end
  # helper_method :current_user_organization

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: 'Please sign in!'
    end
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :find_organization

  def create
    @application = Application.new application_params
    @application.organization = @organization
    if can? :create, @application
      respond_to do |format|
        if @application.update(user: current_user)
          format.html { redirect_to organization_path(@organization), notice: 'Your request has been sent' }
          format.js { render :create_successful }
        else
          format.html { redirect_to organization_path(@organization), alert: 'an Error has occured' }
          format.js { render :create_successful }
        end
      end
    else
      head :unauthorized
    end
  end

  def update
    @application = Application.find(params[:application_id])
      if can? :update, @application
        if params[:id] == '1'
          @application.approve
          flash[:notice] = 'Membership approved'
        else
          @application.reject
          flash[:notice] = 'Membership rejected'
        end
        respond_to do |format|
          if @application.save
            format.html { redirect_to organization_path(@application.organization)}
            format.js { render 'applications/update_succ' }
          else
          end
        end
      else
        head :unauthorized
      end
  end

  def destroy
    application = @organization.applications.find_by(user: current_user)
    if application.destroy
      flash[:notice] = 'Membership cancelled'
    else
      flash[:alert] = 'Error'
    end
    redirect_to organization_path(@organization)
  end

  private

  def find_organization
    @organization = Organization.find(params[:organization_id])
  end

  def application_params
    params.require(:application).permit(:detail)
  end
end

app/helpers/api/application_helper.rb
module Api::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_new.html.erb
<% if user_signed_in? %>
  <% if !current_application.present? %>
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" href="#collapse1">Apply Here</a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
          <div class="panel-body">
              <h2>Apply Here</h2>
              <h4>Additional info</h4>
              <p><%= organization.additional %></p>
              <%= simple_form_for [organization, new_application], remote: true do |f| %>
                <%= f.input :detail %>
                <%= f.submit class:'btn btn-primary', value:'Request' %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/applications/_pending_applications.html.erb
<% organization.pending_applications.each_with_index do |application, k| %>
  <tr id="<%= dom_id(application) %>">
    <td>
      <%=link_to application.user.full_name, user_path(application.user)%>
    </td>
    <td>
      <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#mypModal<%="#{k}" %>">
        Application
      </button>
      <div class="modal fade" id="mypModal<%="#{k}" %>" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Application</h4>
            </div>
            <div class="modal-body">
              <p><%= application.detail%></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </td>
    <td>
      <%= link_to 'Approve', organization_application_membership_path(organization, application, 1), remote: true, method: :patch, class: 'btn btn-success btn-xs' %>
      <%= link_to 'Reject',organization_application_membership_path(organization, application, 0), remote: true, method: :patch, class: 'btn btn-danger btn-xs' %>
    </td>
  </tr>
<% end  %>

app/views/applications/_resolved_applications.html.erb
<% organization.each_with_index do |application, k| %>
  <tr id="<%= dom_id(application) %>">
    <td>
      <%=link_to application.user.full_name, user_path(application.user)%>
    </td>
    <td>
      <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#mypModal<%="#{k}" %>">
        Application
      </button>
      <div class="modal fade" id="mypModal<%="#{k}" %>" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Application</h4>
            </div>
            <div class="modal-body">
              <p><%= application.detail%></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </td>
  </tr>
<% end  %>

app/views/applications/create_successful.js.erb
debugger
$('#application_panel').remove()
$(`<tr id="<%= dom_id(@application) %>">
  <td>
    <%=link_to @application.user.full_name, user_path(@application.user)%>
  </td>
  <td>
    <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#mypModal<%="#{dom_id(@application)}" %>">
      Application
    </button>
    <div class="modal fade" id="mypModal<%="#{dom_id(@application)}" %>" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Application</h4>
          </div>
          <div class="modal-body">
            <p><%= @application.detail%></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </td>
  <td>
    <%= link_to 'Approve', organization_application_membership_path(@organization, @application, 1), remote: true, method: :patch, class: 'btn btn-success btn-xs' %>
    <%= link_to 'Reject',organization_application_membership_path(@organization, @application, 0), remote: true, method: :patch, class: 'btn btn-danger btn-xs' %>
  </td>
</tr>`).prependTo($("#pending_applications")).hide().fadeIn()

app/views/applications/update_succ.js.erb
$('#<%= j dom_id(@application)%> .btn.btn-success').remove()
$('#<%= j dom_id(@application)%> .btn.btn-danger').remove()

if ("<%= @application.rejected? %>" === "true") {
  $("#<%= j dom_id(@application)%>").prependTo($("#rejected_applications")).hide().fadeIn()
} else {
  $("#<%= j dom_id(@application)%>").prependTo($("#approved_applications")).hide().fadeIn()
}