config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :organizations do
    resources :events, except: [:index]
    resources :applications, only: [:create, :destroy, :update] do
      patch '/:id', to: 'applications#update', as: :membership
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :events, only: [] do
    resources :attendances, only: [:create, :destroy]
  end

  resources :users, except: [:destroy]

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  # Api backend routes:

  namespace :api , defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:show, :index]
      resources :organizations, only: [:show, :index]
    end
  end

  namespace :admin do
    resources :organizations,  only: [:index, :update]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization

  has_many :attendances
  has_many :attendees, through: :attendances, source: :user

  def spots_left
    spots - attendees.count
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_organization

  def new
    @event = Event.new
  end

  def create
    @event = Event.new event_params
    @event.organization = @organization
    respond_to do |format|
      if @event.save
        format.html { redirect_to organization_path(@organization), notice: 'Event created' }
        format.js { render :create_success }
      else
        format.html { render :new, alert: 'Event creation Error' }
        format.js { render :create_success }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
    if user_signed_in?
     @org_membership = current_user.memberships.find(@organization.id)
    end
  end

  def destroy
    event = @organization.event
    event.destroy
    flash[:notice] = 'Event cancelled'
    redirect_to organization_path(@organization)
  end

  private

  def find_organization
    @organization = Organization.find(params[:organization_id])
  end

  def event_params
    params.require(:event).permit(:start_date, :end_date, :start_time, :end_time, :details, :spots)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_add_event.html.erb
<%= link_to 'Add new Event', new_organization_event_path(organization), id:'add_event', remote: true if can? :create, organization %>

app/views/events/_events.html.erb
<% if events.present? %>
  <% events.each_with_index do |event, k| %>
    <div class="well well-lg">
      <p><strong>Start date: </strong><%= event.start_date.to_date %></p>
      <p><strong>End date: </strong><%= event.end_date.to_date %></p>
      <p><strong>available spots: </strong><%= event.spots_left %></p>
      <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal<%="#{k}" %>">
        More info
      </button>
      <div class="modal fade" id="myModal<%="#{k}" %>" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Details</h4>
            </div>
            <div class="modal-body">
              <p><%= event.details%></p>
              <p><%= link_to 'Event page', organization_event_path(@organization, event) %></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/_new.html.erb
<div>
  <%= simple_form_for [@organization, @event], remote: true do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.input :spots %>
  <%= f.input :details %>
  <%= f.submit %>
  <% end %>
</div>

app/views/events/create_success.js.erb
document.querySelector('#event').outerHTML='<%= j render "events", events: @organization.events %>'
$('#new_event').remove()
$('#add_event').show()

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/new.html.erb
<div class="container">
  <div class="col-lg-4">
    <%= simple_form_for [@organization, @event] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
    <%= f.input :spots %>
    <%= f.input :details %>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/events/new.js.erb
$('#add_event').hide().after('<%= j render("events/new") %>')

app/views/events/show.html.erb
<div class="container">
  <p><%= @event.details %></p>

  <div class="row">
    <% if user_signed_in? %>
      <% if @org_membership&.approved? %>
        <h2>Apply</h2>
        <%= link_to 'Join', event_attendances_path(@event), class:"btn btn-primary", method: :post %>
        <%= link_to 'Cancel', event_attendance_path(@event), class:"btn btn-danger", method: :delete %>
      <%end %>
    <% end %>
  </div>
</div>