config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :organizations do
    resources :events, except: [:index]
    resources :applications, only: [:create, :destroy, :update] do
      patch '/:id', to: 'applications#update', as: :membership
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :events, only: [] do
    resources :attendances, only: [:create, :destroy]
  end

  resources :users, except: [:destroy]

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  # Api backend routes:

  namespace :api , defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:show, :index]
      resources :organizations, only: [:show, :index]
    end
  end

  namespace :admin do
    resources :organizations,  only: [:index, :update]
  end
end

app/models/organization.rb
class Organization < ApplicationRecord

  belongs_to :user

  has_many :applications, dependent: :destroy
  has_many :applicants, through: :applications, source: :user

  has_many :events, dependent: :destroy

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true

  scope :approved_organizations, lambda { where(aasm_state: 'approved') }
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }

  geocoded_by :address
  after_validation :geocode

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  accepts_nested_attributes_for :events,
                                reject_if: :all_blank,
                                allow_destroy: true

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end


  end


  def approved_applications
    self.applications.where(aasm_state: 'approved')
  end

  def rejected_applications
    self.applications.where(aasm_state: 'rejected')
  end

  def pending_applications
    self.applications.where(aasm_state: 'pending')
  end

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::BaseController
  def index
    @organizations = Organization.order(created_at: :desc)
  end

  def update
    @organization = Organization.find(params[:id])

    if params[:approve]
      @organization.approve
      flash[:notice] = 'Membership approved'
    else
      @organization.reject
      flash[:notice] = 'Membership rejected'
    end

    respond_to do |format|
      if @organization.save
        format.html { redirect_to admin_organizations_path }
        format.js { render :update_success }
      else
        format.html { redirect_to admin_organizations_path }
        format.js { render :update_success }
      end
    end
  end
end

app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < Api::ApplicationController
  before_action :authenticate_user!
  before_action :find_organization, only: [:show]

  def index
    # render json: current_user
    render json: Organization.approved
  end

  def show
    render json:@organization
  end

  private

  def find_organization
    @organization = Organization.find(params[:id])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_organization, only: [:show, :edit, :update]

  def index
    @organizations = Organization.approved
    # @organization =  @organizations.near([49.2819605,-123.1086604], 1000)
    @hash = Gmaps4rails.build_markers(@organizations) do |organization, marker|
      marker.lat organization.latitude
      marker.lng organization.longitude
      marker.infowindow organization.name
    end
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new organization_params
    @organization.user = current_user
    if @organization.save
      redirect_to organization_path(@organization)
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @organization.reviews.order(created_at: :desc)
    @new_application = Application.new
    @current_application = @organization.applications.find_by(user_id: current_user)
    @events = @organization.events
    @event = Event.new

    @org_rating = 0
    if !@reviews.empty?
      @reviews.each do |r|
        @org_rating+= r.rating.to_i
      end
      @org_rating=@org_rating/@reviews.count
    end
  end

  def edit
  end

  def update
    if can? :update, @organization
      respond_to do |format|
        if @organization.update params.require(:organization).permit(pictures: [])
            format.html { redirect_to organization_path(@organization) }
            format.js { render :update_successful }
        else
          render :edit
        end
      end
    else
      head :unauthorized
    end
  end



  private

  def organization_params
    params.require(:organization).permit(:name, :website, :phone, :address, :additional, pictures: [],
      events_attributes: [:start_date,
        :end_date,
        :start_time,
        :end_time,
        :spots,
        :details ] )
      end

  def find_organization
    @organization = Organization.find(params[:id])
  end

end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/api/v1/organizations_helper.rb
module Api::V1::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_add_picture.html.erb
<br>
<p id='add_picture'><%= link_to 'Add pictures', edit_organization_path(organization), remote: true %></p>

app/views/organizations/_edit.html.erb
<br>
<%= simple_form_for @organization, remote: true, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.file_field :pictures, multiple: true , class:'form-control'%>
  </div>
  <%= f.submit({class: "btn btn-primary"}) %>
<% end %>

app/views/organizations/_event_fields.html.erb
<div class="nested-fields">
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.input :spots %>
  <%= f.input :details %>
  <%= link_to_remove_association "remove event", f %>
</div>

app/views/organizations/_pictures.html.erb
<% organization.pictures&.each do |picture| %>
  <%= image_tag picture.url(:medium), class: 'img-rounded', alt:"Cinque Terre" %>
<% end %>

app/views/organizations/edit.js.erb
$('#add_picture').hide().after('<%= j render("edit") %>');

app/views/organizations/index.html.erb
<div class="container">
  <div class="col-lg-4">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Organization</th>
        </tr>
      </thead>
      <tbody>
        <% @organizations.each do |organization| %>
            <tr><td><%=link_to "#{organization.name}", organization_path(organization) %></td></tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-lg-6 col-lg-offset-2">
    <div id="map" class='well well-lg' style='height: 400px;'></div>
  </div>
</div>

<!-- script goes here -->

<script>
  handler = Gmaps.build('Google');
   handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers(<%= raw @hash.to_json %>);
   handler.bounds.extendWith(markers);
   handler.fitMapToBounds();
   });
</script>

app/views/organizations/new.html.erb
<%= simple_form_for @organization, html: { multipart: true } do |f| %>
  <div class="container">
    <h1>Organizations Sign up</h1>
    <hr>
    <div class="col-lg-4">
      <%= f.input :name %>
      <%= f.input :website, as: :url %>
      <%= f.input :address %>
      <%= f.input :phone, as: :tel %>
      <%= f.input :additional, label:'additional info' %>
      <div class="form-group">
        <%= f.file_field :pictures, multiple: true , class:'form-control'%>
      </div>

      <%= f.simple_fields_for :events do |r| %>
       <%= render 'event_fields', f: r %>
      <% end %>

     <div class="links">
       <%= link_to_add_association 'add event', f, :events %>
     </div>
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/organizations/show.html.erb
<div class="container">
  <!-- Organization details section -->
  <div class="row">
    <h1><%= @organization.name %></h1>
    <div class="col-lg-6">
      <div class="row">
        <p><strong>Review: </strong><%= @org_rating%></p>
        <p><strong>Address: </strong><%= @organization.address %></p>
        <p><strong>Website: </strong><a href="http://<%= @organization.website%>"><%= @organization.website %></a></p>
        <!-- Organiation appliacation status -->
        <% if user_signed_in? %>
        <% if @current_application.present? %>
        <p><strong id='status'>Membership status: </strong><%= @current_application.aasm_state %></p>
        <% else %>
        <p><strong id='status'>Membership status: </strong>Not applied yet</p>
        <% end %>
        <% if @current_application&.approved? %>
        <%= link_to 'Leave organization', organization_application_path(@organization), class:"btn btn-danger btn-sm", method: :delete %>
        <% end %>
        <% end %>
      </div>
      <br>
      <!-- Images section -->
      <div class="row" id='images'>
        <%= render 'organizations/pictures' , organization: @organization %>
        <br>
      <% if can? :edit, @organization %>
        <%= render 'organizations/add_picture', organization: @organization %>
      <% end %>
      </div>
    </div>
<!-- Map  -->
    <div class='col-lg-6' >
      <div id="map" class='well well-lg' style='height: 400px;'></div>
    </div>
  </div>
  <hr>
  <div class="row">
    <h2>Events</h2>
    <div class="col-lg-6">
      <!-- Events sections -->
      <div class="row">
        <div id='event'>
          <%= render 'events/events', events: @events %>
        </div>
        <%= render 'events/add_event', organization: @organization %>
      </div>
    </div>
<!-- Application Area -->
    <div class="col-lg-6" id='application_panel'>
      <%= render 'applications/new', {organization: @organization,
                                      current_application: @current_application,
                                      new_application: @new_application} %>
    </div>
  </div>

  <div class="row">
    <h2>Reviews</h2>
    <hr>
    <div class="row">
      <div class="col-lg-6">
        <% @reviews.each do |review| %>
        <p><strong>stars: </strong><%= review.rating %></p>
        <p><%= review.body %></p>
        <p><strong><%= review.user.full_name %></strong></p>
        <hr>
        <% end  %>
      </div>
      <% if user_signed_in? && @current_application&.approved? %>
        <div class="col-lg-6">
          <%= simple_form_for [@organization, @review] do |f| %>
            <%= f.input :body  %>
            <%= f.input :rating, collection: 1..5 %>
            <%= f.submit %>
          <% end  %>
        </div>
      <% end  %>
    </div>
  </div>
  <!-- Org member managemenent section -->
  <%# if @organization.user == current_user %>
  <% if can? :create, @organization %>
    <div class="row">
      <h2>Manage</h2>
      <hr>
      <!-- pending memebrs list -->
      <div class="col-lg-4">
        <table class='table table-hover'>
          <thead>
            <tr>
              <th>Pending</th>
            </tr>
          </thead>
          <tbody id='pending_applications'>
              <%= render 'applications/pending_applications', organization: @organization %>
          <tbody>
        </table>
      </div>
      <!-- approved memebrs list -->
      <div class="col-lg-4">
        <table class='table table-hover'>
          <thead>
            <tr>
              <th>Approved</th>
            </tr>
          </thead>
          <tbody id='approved_applications'>
              <%= render 'applications/resolved_applications', organization: @organization.approved_applications %>
          <tbody>
        </table>
      </div>
      <!-- Rejected memebrs list -->
      <div class="col-lg-4">
        <table class='table table-hover'>
          <thead>
            <tr>
              <th>Rejected</th>
            </tr>
          </thead>
          <tbody id='rejected_applications' >
              <%= render 'applications/resolved_applications', organization: @organization.rejected_applications %>
          <tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

<!--////////////////////////////////////////////////////////////////////////////  -->
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @organization.latitude %>,
      "lng": <%= @organization.longitude %>,
      "infowindow": "<%= @organization.name %>"
    },

  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(20);
  });
</script>

app/views/organizations/update_successful.js.erb
document.querySelector('#images').innerHTML = '<%= j render "pictures", organization: @organization  %>'
$('#images').append('<%= j render "add_picture", organization: @organization %>')