config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :organizations do
    resources :events, except: [:index]
    resources :applications, only: [:create, :destroy, :update] do
      patch '/:id', to: 'applications#update', as: :membership
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :events, only: [] do
    resources :attendances, only: [:create, :destroy]
  end

  resources :users, except: [:destroy]

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  # Api backend routes:

  namespace :api , defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:show, :index]
      resources :organizations, only: [:show, :index]
    end
  end

  namespace :admin do
    resources :organizations,  only: [:index, :update]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arj Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyAjRb127BJTTM60T16p9WcsIoo_4RLYBlA"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <nav class="navbar navbar-default" id='navbar'>
      <div class="container-fluid">
        <div class="row">
          <div class="navbar-header">
            <a href='/' class='navbar-brand fa fa-handshake-o fa-2x'><span id='project-logo-text'> Arj Project<span></a>
          </div>
            <ul class='nav navbar-nav navbar-right' id='navbar-right'>
              <li><%= link_to "Organizations", organizations_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to 'My profile', user_path(current_user) %></li>
              <% if current_user.organizations.present?%>
              <li><%= link_to 'Organization panel', organization_path(current_user.organizations[0]) %></li>
              <% end %>
              <% if current_user.is_admin %>
              <li><%# link_to "Admin panel", admin_panel_path %></li>
              <% end %>
              <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
              <li class='active'><a href='#'>Hello <%= current_user.full_name %></a></li>
              <% else %>
              <li><%= link_to "Sign in", new_session_path %></li>
              <li><%= link_to "Sign up", new_user_path %></li>
              <% end  %>
            </ul>
        </div>
      </div>
    </nav>
    <div id="flash-message">
      <% if flash[:notice] %>
        <div class='alert alert-success'><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class='alert alert-danger'><%= flash[:alert] %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>